// // AUTO-GENERATED FILE.
// // This file is auto-generated by the Ballerina OpenAPI tool.

// import ballerina/http;
// import ballerina/test;
// import ballerina/oauth2; 

// configurable string clientId = ?;
// configurable string clientSecret = ?;
// configurable string refreshToken = ?;
// configurable string serviceUrl = ?; 

// OAuth2RefreshTokenGrantConfig authConfig = {
//        clientId: clientId,
//        clientSecret: clientSecret,
//        refreshToken: refreshToken,
//        credentialBearer: oauth2:POST_BODY_BEARER
//    };


// // configurable http:BearerTokenConfig & readonly authConfig = ?;
// ConnectionConfig config = {auth : authConfig};
// Client baseClient = check new Client(config, serviceUrl = "https://api.hubapi.com");

// @test:Config {}
// isolated function  testPost-/crm/v3/objects/quotes/batch/archive/archive() {
//     json payload = {};
//     var response = baseClient->post("/crm/v3/objects/quotes/batch/archive", payload);
//     test:assertEquals(response is http:Response, true, msg = "Response is not HTTP response");
//     test:assertEquals(response.getJsonPayload(), {"message": "Batch quotes archived successfully."});
// }

// @test:Config {}
// isolated function  testPost-/crm/v3/objects/quotes_create() {
// }

// @test:Config {}
// isolated function  testGet-/crm/v3/objects/quotes_getPage() {
// }

// @test:Config {}
// isolated function  testDelete-/crm/v3/objects/quotes/{quoteId}_archive() {
// }

// @test:Config {}
// isolated function  testPatch-/crm/v3/objects/quotes/{quoteId}_update() {
// }

// @test:Config {}
// isolated function  testGet-/crm/v3/objects/quotes/{quoteId}_getById() {
// }

// @test:Config {}
// isolated function  testPost-/crm/v3/objects/quotes/batch/update_update() {
// }

// @test:Config {}
// isolated function  testPost-/crm/v3/objects/quotes/batch/upsert_upsert() {
// }

// @test:Config {}
// isolated function  testPost-/crm/v3/objects/quotes/batch/create_create() {
// }

// @test:Config {}
// isolated function  testPost-/crm/v3/objects/quotes/search_doSearch() {
// }

// @test:Config {}
// isolated function  testPost-/crm/v3/objects/quotes/batch/read_read() {
// }
